### ISSUE TITLE
Globally provide pycharm.desktop

### ISSUE THREAD

**Issue by polymeter** [saltstack-formulas/jetbrains-pycharm-formula#3]
Hi,

I'm currently using the formula on Debian stretch (with pycharm and pycharm.linuxenv, alternatives enabled) and it works fine.
However, Gnome's launcher (and possibly other places) doesn't show pycharm, apparently because it only displays choices that have a .desktop file in /usr/share/applications/. I put the existing pycharm.desktop (from the repo) there and it worked right away. This seems to be independent of the actions defined in linuxenv.sls, i.e. neither the PATH approach nor the alternatives approach are required for it to work.

Does it make sense to include this in the formula? And if so, should it be a separate state or included in linuxenv.sls? Thanks!

**Comment by noelmcloughlin** [comment]
Hi @polymeter thanks for reporting this issue.  Yes, it makes complete sense to fix this. Gnome should be supported.  The `developer.sls` file includes `pycharm-desktop-shortcut-add` for MacOS, and `pycharm-desktop-shortcut-install` state for Linux (Cross OS desktop icon handling).  You are welcome to submit a PR for whatever solution you want to try.  Thx!!

**Comment by polymeter** [comment]
Done via #4. Thanks for merging!

**Comment by noelmcloughlin** [comment]
Hey @polymeter The same fix is required in [few formulas](https://github.com/saltstack-formulas?utf8=%E2%9C%93&q=jetbrains+OR+intellij&type=&language=) if you are interested in submitting same PR.  Otherwise, I'll do myself sometime - just letting you know.

**Comment by polymeter** [comment]
Hey, sorry, I was on vacation for a few days. I'll try to look into the other formulas some time and keep you informed.

**Comment by noelmcloughlin** [comment]
Hi @polymeter no worries - I found some time to update them already.  However, any future PR for  Pycharm formula can be cloned to all jetbrains formulae - they are code clones!
